aws-ia/terraform-aws-eks-data-addons

README.md
- Readme update with more ML add-ons examples
=> docs: Updated readme with more examples

spark-history-server.tf
-- Setting Create IRSA is true by default. Users can pass thier own S3 policies if required
-- service account create is true by default so removing this one
=> feat: Updates to SHS service account setup

README.md, kuberay-operator.tf, outputs.tf, test/main.tf, variables.tf
Adds helm-release for kuberay-operator as we have started to create additional blueprints in data-on-eks repo for ai/ml that will be using Ray.
=> feat: Add kuberay-operator add-on

README.md, cnpg-operator.tf, variables.tf
- [x ] Yes, I ran `pre-commit run -a` with this PR
=> feat: Adding CloudNativePG addon to the repo

README.md, dask-hub.tf, dask-operator.tf, outputs.tf, variables.tf
- Resolves [#67](https://github.com/awslabs/data-on-eks/issues/67)
Add dask-operator and dask-hub addon on EKS.
=> feat: Add dask-operator and dask-hub addons

README.md, outputs.tf, pinot.tf, variables.tf
=> feat: Adding apache pinot support

pinot.tf
- Fixes issue with helm config
=> fix: Pinot helm release name param error

strimzi-kafka-operator.tf
=> chore: Update Strimzi Kafka version

spark-history-server.tf
=> Update the new org name for spark history server

helm-charts/karpenter-resources/templates/node-class.yaml, helm-charts/karpenter-resources/values.yaml
- Added RAID0 support to the Karpenter template
- 
=> Added RAIDO config for karpenter templates

helm-charts/mlflow-tracking/Chart.yaml, helm-charts/mlflow-tracking/Dockerfile, helm-charts/mlflow-tracking/values.yaml, mlflow-tracking.tf
=> chore: MLflow version update

helm-charts/neuron-device-plugin/values.yaml, spark-operator.tf
- NVIDIA Device plugin updated to latest version 
- Spark Operator is now using the latest repo URL
=> feat: Nvidia device plugin and Spark Operator addon update

emr-flink-operator.tf
Adds property to pass operator IAM role
Creating a blueprint for EMR Flink on EKS
- Resolves #32
=> feat: Add property to pass EMR operatorExecutionRoleArn

emr-flink-operator.tf
Fixed the default value of the repository
- Resolves #34
=> feat: Fixed emr flink repo default value

spark-history-server.tf, spark-operator.tf
Update Spark Operator helm chart to version 1.2.15
Update Spark History Server docker image for arm64 compatibility
=> feat: Spark update

helm-charts/nvidia-triton-server/templates/hpa.yaml, helm-charts/nvidia-triton-server/values.yaml
Adds hpa configuration for triton server autoscaling
Adds hpa configuration for triton server autoscaling
=> feat: Add hpa config for triton server 

.pre-commit-config.yaml, README.md, irsa/README.md, test/README.md
- Add clarifying support disclaimer like the original/main project
=> chore: Add clarifying support disclaimer like the original/main project

helm-charts/karpenter-resources/Chart.yaml, helm-charts/karpenter-resources/templates/node-class.yaml, helm-charts/karpenter-resources/templates/node-pool.yaml, helm-charts/karpenter-resources/values.yaml
Updating the Karpenter resources to v1 following the guidance from this blog: https://aws.amazon.com/blogs/containers/announcing-karpenter-1-0/
- Resolves #44
=> feat: Update resources to Karpenter v1 #44

helm-charts/neuron-device-plugin/Chart.yaml, helm-charts/neuron-device-plugin/values.yaml
Bump up neuron device plugin to latest version.
=> feat: Bump up neuron device plugin version

flink-operator.tf
Updates flink operator helm chart config with correct 1.10.0 version.
=> fix: Update flink operator helm config

nvidia-gpu-operator.tf
This updated chart fixes the issues found in https://github.com/NVIDIA/dcgm-exporter/issues/412
=> fix: Update nvidia-gpu-operator.tf
